-- ============================================
-- SecureInsights Hub - Database Setup
-- Privacy-Preserving AI Collaboration Platform
-- ============================================

-- Create separate databases for each organization (simulating multi-org setup)
-- In production, each org would have their own Snowflake account

-- Organization A: Bank
CREATE DATABASE IF NOT EXISTS SECUREINSIGHTS_BANK;
CREATE SCHEMA IF NOT EXISTS SECUREINSIGHTS_BANK.PRIVATE_DATA;
CREATE SCHEMA IF NOT EXISTS SECUREINSIGHTS_BANK.SHARED_VIEWS;

-- Organization B: Insurance Company
CREATE DATABASE IF NOT EXISTS SECUREINSIGHTS_INSURANCE;
CREATE SCHEMA IF NOT EXISTS SECUREINSIGHTS_INSURANCE.PRIVATE_DATA;
CREATE SCHEMA IF NOT EXISTS SECUREINSIGHTS_INSURANCE.SHARED_VIEWS;

-- Organization C: Public Agency (Subsidies)
CREATE DATABASE IF NOT EXISTS SECUREINSIGHTS_AGENCY;
CREATE SCHEMA IF NOT EXISTS SECUREINSIGHTS_AGENCY.PRIVATE_DATA;
CREATE SCHEMA IF NOT EXISTS SECUREINSIGHTS_AGENCY.SHARED_VIEWS;

-- Clean Room Database (where collaboration happens)
CREATE DATABASE IF NOT EXISTS SECUREINSIGHTS_CLEANROOM;
CREATE SCHEMA IF NOT EXISTS SECUREINSIGHTS_CLEANROOM.ANALYTICS;
CREATE SCHEMA IF NOT EXISTS SECUREINSIGHTS_CLEANROOM.AUDIT;
CREATE SCHEMA IF NOT EXISTS SECUREINSIGHTS_CLEANROOM.PLAYBOOKS;

-- Warehouse for processing
CREATE WAREHOUSE IF NOT EXISTS SECUREINSIGHTS_WH
    WAREHOUSE_SIZE = 'SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

USE WAREHOUSE SECUREINSIGHTS_WH;
