-- ============================================
-- Snowflake Horizon Governance Setup
-- Tags and role-based access control
-- ============================================

USE DATABASE SECUREINSIGHTS_CLEANROOM;

-- ============================================
-- Object Tags for Data Classification
-- ============================================

CREATE OR REPLACE TAG DATA_SENSITIVITY
    ALLOWED_VALUES 'PUBLIC', 'INTERNAL', 'CONFIDENTIAL', 'RESTRICTED'
    COMMENT = 'Classification level of data sensitivity';

CREATE OR REPLACE TAG DATA_CATEGORY
    ALLOWED_VALUES 'PII', 'FINANCIAL', 'HEALTH', 'DEMOGRAPHIC', 'AGGREGATED'
    COMMENT = 'Type of data contained';

CREATE OR REPLACE TAG ETHICAL_USE
    ALLOWED_VALUES 'APPROVED', 'RESTRICTED', 'PROHIBITED'
    COMMENT = 'Ethical use classification';

CREATE OR REPLACE TAG DATA_OWNER
    COMMENT = 'Organization that owns the source data';

-- ============================================
-- Apply Tags to Private Data Tables
-- ============================================

ALTER TABLE SECUREINSIGHTS_BANK.PRIVATE_DATA.CUSTOMERS
    SET TAG DATA_SENSITIVITY = 'RESTRICTED',
        DATA_CATEGORY = 'FINANCIAL',
        ETHICAL_USE = 'PROHIBITED',
        DATA_OWNER = 'BANK';

ALTER TABLE SECUREINSIGHTS_INSURANCE.PRIVATE_DATA.POLICYHOLDERS
    SET TAG DATA_SENSITIVITY = 'RESTRICTED',
        DATA_CATEGORY = 'FINANCIAL',
        ETHICAL_USE = 'PROHIBITED',
        DATA_OWNER = 'INSURANCE';

ALTER TABLE SECUREINSIGHTS_AGENCY.PRIVATE_DATA.BENEFICIARIES
    SET TAG DATA_SENSITIVITY = 'RESTRICTED',
        DATA_CATEGORY = 'DEMOGRAPHIC',
        ETHICAL_USE = 'PROHIBITED',
        DATA_OWNER = 'AGENCY';

-- ============================================
-- Apply Tags to Clean Room Views (Approved)
-- ============================================

ALTER VIEW SECUREINSIGHTS_CLEANROOM.ANALYTICS.BANK_AGGREGATES
    SET TAG DATA_SENSITIVITY = 'INTERNAL',
        DATA_CATEGORY = 'AGGREGATED',
        ETHICAL_USE = 'APPROVED';

ALTER VIEW SECUREINSIGHTS_CLEANROOM.ANALYTICS.INSURANCE_AGGREGATES
    SET TAG DATA_SENSITIVITY = 'INTERNAL',
        DATA_CATEGORY = 'AGGREGATED',
        ETHICAL_USE = 'APPROVED';

ALTER VIEW SECUREINSIGHTS_CLEANROOM.ANALYTICS.AGENCY_AGGREGATES
    SET TAG DATA_SENSITIVITY = 'INTERNAL',
        DATA_CATEGORY = 'AGGREGATED',
        ETHICAL_USE = 'APPROVED';

ALTER VIEW SECUREINSIGHTS_CLEANROOM.ANALYTICS.COMBINED_RISK_INSIGHTS
    SET TAG DATA_SENSITIVITY = 'INTERNAL',
        DATA_CATEGORY = 'AGGREGATED',
        ETHICAL_USE = 'APPROVED';

-- ============================================
-- Access Roles
-- ============================================

CREATE ROLE IF NOT EXISTS SECUREINSIGHTS_ADMIN;
CREATE ROLE IF NOT EXISTS SECUREINSIGHTS_ANALYST;
CREATE ROLE IF NOT EXISTS SECUREINSIGHTS_VIEWER;

-- Admin gets full access
GRANT USAGE ON DATABASE SECUREINSIGHTS_CLEANROOM TO ROLE SECUREINSIGHTS_ADMIN;
GRANT USAGE ON ALL SCHEMAS IN DATABASE SECUREINSIGHTS_CLEANROOM TO ROLE SECUREINSIGHTS_ADMIN;
GRANT SELECT ON ALL TABLES IN DATABASE SECUREINSIGHTS_CLEANROOM TO ROLE SECUREINSIGHTS_ADMIN;
GRANT SELECT ON ALL VIEWS IN DATABASE SECUREINSIGHTS_CLEANROOM TO ROLE SECUREINSIGHTS_ADMIN;

-- Analyst can run playbooks and see aggregates
GRANT USAGE ON DATABASE SECUREINSIGHTS_CLEANROOM TO ROLE SECUREINSIGHTS_ANALYST;
GRANT USAGE ON SCHEMA SECUREINSIGHTS_CLEANROOM.ANALYTICS TO ROLE SECUREINSIGHTS_ANALYST;
GRANT USAGE ON SCHEMA SECUREINSIGHTS_CLEANROOM.PLAYBOOKS TO ROLE SECUREINSIGHTS_ANALYST;
GRANT USAGE ON SCHEMA SECUREINSIGHTS_CLEANROOM.AUDIT TO ROLE SECUREINSIGHTS_ANALYST;
GRANT SELECT ON ALL VIEWS IN SCHEMA SECUREINSIGHTS_CLEANROOM.ANALYTICS TO ROLE SECUREINSIGHTS_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA SECUREINSIGHTS_CLEANROOM.PLAYBOOKS TO ROLE SECUREINSIGHTS_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA SECUREINSIGHTS_CLEANROOM.AUDIT TO ROLE SECUREINSIGHTS_ANALYST;

-- Viewer can only see combined insights
GRANT USAGE ON DATABASE SECUREINSIGHTS_CLEANROOM TO ROLE SECUREINSIGHTS_VIEWER;
GRANT USAGE ON SCHEMA SECUREINSIGHTS_CLEANROOM.ANALYTICS TO ROLE SECUREINSIGHTS_VIEWER;
GRANT SELECT ON VIEW SECUREINSIGHTS_CLEANROOM.ANALYTICS.COMBINED_RISK_INSIGHTS TO ROLE SECUREINSIGHTS_VIEWER;

-- Grant warehouse usage
GRANT USAGE ON WAREHOUSE SECUREINSIGHTS_WH TO ROLE SECUREINSIGHTS_ADMIN;
GRANT USAGE ON WAREHOUSE SECUREINSIGHTS_WH TO ROLE SECUREINSIGHTS_ANALYST;
GRANT USAGE ON WAREHOUSE SECUREINSIGHTS_WH TO ROLE SECUREINSIGHTS_VIEWER;

-- ============================================
-- Query to verify tags
-- ============================================
-- SELECT * FROM TABLE(INFORMATION_SCHEMA.TAG_REFERENCES_ALL_COLUMNS('SECUREINSIGHTS_CLEANROOM.ANALYTICS.COMBINED_RISK_INSIGHTS', 'VIEW'));
